### ISSUE TITLE
Update pyglotaran-extras to target new API

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran-extras#7]
A tagged release was made to preserve the package in a state that is compatible with v0.3.x, download [here](https://github.com/glotaran/pyglotaran-extras/releases/tag/v0.3.3).

With this done, the examples can be updated to target the new API introduced by pyglotaran 0.4.

**Comment by jsnel** [comment]
Presumably this issue can be closed

**Comment by s-weigand** [comment]
The extras work with the current stable and development version of `pyglotaran` so this can be closed
